import os
from typing import Any, Dict

from tools.agent_tools import _resolve_path


class SpecialistManager:
    """
    Handles invocations of specialist LLM workers for high-complexity,
    unstructured generation tasks like writing or patching files.
    """

    def __init__(self, connector: Any, specialist_config: Dict[str, str]):
        """
        Initializes the SpecialistManager.

        Args:
            connector (Any): The LLM connector used to send requests to the models.
            specialist_config (Dict[str, str]): A dictionary mapping tool names to specialist role descriptions.
        """
        self.connector = connector
        self.config = specialist_config

    def is_specialist_tool(self, tool_name: str) -> bool:
        """Checks if a tool is designated for a specialist."""
        return tool_name in self.config

    def invoke(self, tool_name: str, params: Dict[str, Any]) -> str:
        """
        Invokes the specialist worker to generate raw text output.

        Args:
            tool_name (str): The name of the tool, used to look up the specialist's role.
            params (Dict[str, Any]): The parameters for the tool, containing the goal and target path.

        Returns:
            str: The raw text output generated by the specialist.
        """
        role_description = self.config[tool_name]
        goal = params.get("instructions") or params.get("content") or params.get("replace") or "Complete task."
        path = params.get("path", "unknown")

        current_state = "File does not exist yet or is empty."
        try:
            resolved_path = _resolve_path({"path": path})
            if os.path.exists(resolved_path):
                with open(resolved_path, 'r', encoding='utf-8') as f:
                    current_state = f.read()[:3000]
        except Exception:
            pass

        worker_payload = {
            "task_context": f"File Target: {path}\n\nCurrent State:\n{current_state}\n\nGoal:\n{goal}",
            "instruction": "Output raw text only. Do not use markdown blocks or explanations."
        }
        raw_output_stream = self.connector.send_raw_request(worker_payload, system_prompt=role_description)
        return "".join(list(raw_output_stream)).strip()